### ISSUE TITLE
Reload

### ISSUE THREAD

**Issue by nassan** [amitairos/Lasso#1]
Reloading the app on `http://localhost:4200/#/Create/0bca8fae-9e18-1f84-2680-3935943e2b32` results in a redirect to login, and then to main if logged in, ideally it should know it is logged in, and only do that redirect if it is not logged in

Is this something that we should fix?

**Comment by amitairos** [comment]
Yes. It should be fixed. It originated from the fact that we wanted that the browser won't save the session. But reloading shouldn't log out. This is connected to the Auth-Guard that I used, which needs to be changed a bit.
