### ISSUE TITLE
Clicking on Preview and Submit causes the system to freeze

### ISSUE THREAD

**Issue by yisraelr** [amitairos/Lasso#10]
According to Eli, when clicking on Preview & Submit the system freezes. I tried it, and it works. I'm afraid that this has to do with the popup disabling that Eli has. I'm not sure. Can you see if this is indeed the case, and if it has to do with popup disabling, open it in a different window mode?
I'm referring to this:
![image](https://user-images.githubusercontent.com/47521159/52916409-c8404480-32e7-11e9-9189-0001e2e64e66.png)

**Comment by nassan** [comment]
Now that I am going through the code I see a number of places where crashes like this could potentially be a problem. I fixed the one that we could see from the browser console from the call stack. No guarantee that this solves all of them, but it should solve the one we saw on Skype.
