### ISSUE TITLE
Cost fields added for Home modifications, housekeeeping services, and home health aid

### ISSUE THREAD

**Issue by nassan** [amitairos/Lasso#6]

**Comment by yisraelr** [comment]
Housekeeping cost do not appear on the Preview form.
![image](https://user-images.githubusercontent.com/47521159/52620281-cec85980-2eac-11e9-80e6-1d4b65c354b7.png)

**Comment by yisraelr** [comment]
Are calculations updated too? I mean, does it take the added cost fields also when it calculates?

**Comment by nassan** [comment]
Now they should.
