### ISSUE TITLE
American style dates

### ISSUE THREAD

**Issue by nassan** [amitairos/Lasso#7]
for lifecare planner create form date of loss and date of birth, as we as on the dashboard, inside each expansion planner

**Comment by yisraelr** [comment]
American style date should be on each field of the form. Example:
![image](https://user-images.githubusercontent.com/47521159/52620405-2b2b7900-2ead-11e9-924b-0683404b052c.png)

**Comment by nassan** [comment]
Okay I add the format to the placeholders.

**Comment by yisraelr** [comment]
Looks good. In  case we see anther place to update the date label, we'll reopen.
